// "NanoBanana" es el alias interno para el modelo de imágenes de Gemini 2.5 Flash.
// Integramos directamente con la API oficial de Gemini para generación/edición de imagen
// usando el modelo "gemini-2.5-flash-image-preview" (configurable por env).

export type NanoStep = "m4" | "m8" | "m12";

async function fetchImageAsInlineData(url: string): Promise<{ mimeType: string; data: string }> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed fetching base image: ${res.status}`);
  const mimeType = res.headers.get("content-type") || "image/jpeg";
  const arrayBuffer = await res.arrayBuffer();
  const data = Buffer.from(arrayBuffer).toString("base64");
  return { mimeType, data };
}

export async function generateTransformedImage(params: {
  imageUrl: string; // Signed URL to original in Firebase Storage
  profile: {
    age: number;
    sex: "male" | "female" | "other";
    heightCm: number;
    weightKg: number;
    level: "novato" | "intermedio" | "avanzado";
    goal: "definicion" | "masa" | "mixto";
    weeklyTime: number;
    notes?: string;
  };
  step: NanoStep; // which month projection
  aiPrompt?: string; // The specific visual prompt generated by Gemini
}): Promise<{ buffer: Buffer; contentType: string }> {
  const apiKey = process.env.GEMINI_API_KEY;
  const model = process.env.GEMINI_IMAGE_MODEL || "gemini-2.5-pro-image-preview";
  if (!apiKey) throw new Error("Missing GEMINI_API_KEY for NanoBanana (Gemini 2.5 Flash Image)");

  const { mimeType, data } = await fetchImageAsInlineData(params.imageUrl);

  // Prompt enfocado a cambios realistas y consistentes con NGX
  const goalMap = {
    definicion: "shredded, extremely low body fat, visible abs, vascularity, defined jawline, lean face",
    masa: "massive muscle hypertrophy, bodybuilder physique, broad shoulders, thick chest, powerful arms, thick neck",
    mixto: "athletic superhero physique, perfect proportions, lean and muscular, functional strength, wide shoulders"
  };
  const aggressiveBase = goalMap[params.profile.goal] || "athletic fitness transformation";

  // REVERT TO PURE NIKE STYLE (User Preference: "INCREIBLE")
  // We ignore the specificDetails to prevent dilution of the aesthetic.
  // The Visual Timeline input still drives the Text Insights, but the Image is pure Aspirational.

  // STRATEGY: Premium Cinematic (Nike/Adidas Commercial Style)
  const prompt = `GENERATE A NEW IMAGE based on this person.
  
  TRANSFORMATION TARGET: ${aggressiveBase}
  
  CRITICAL INSTRUCTION:
  Create a MASTERPIECE of fitness photography.
  Style: "NIKE ADVERTISEMENT", "CINEMATIC LIGHTING", "HIGH CONTRAST", "PROFESSIONAL COLOR GRADING".
  
  1. FACE: Keep the identity perfectly.
  2. BODY: REPLACE with a world-class athlete physique matching the target.
  3. ATMOSPHERE: Intense, gritty but clean, dramatic shadows, volumetric lighting (God rays).
  4. CLOTHING: Premium athletic wear (Under Armour/Nike style) or shirtless to show definition.
  5. DETAILS: Sweat, skin texture, veins, determined expression.
  
  If the output looks like a snapshot or selfie, YOU HAVE FAILED.
  MAKE IT LOOK LIKE A BILLBOARD CAMPAIGN.`;

  console.log("🍌 NanoBanana Prompt:", prompt);

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const body = {
    contents: [
      {
        role: "user",
        parts: [
          { text: prompt },
          { inlineData: { mimeType, data } }, // imagen base para image-to-image
        ],
      },
    ],
    generationConfig: {
      // responseMimeType removed as it causes INVALID_ARGUMENT
    },
    safetySettings: [
      { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" },
    ],
  } as const;

  console.log("🍌 Sending request to Gemini...");
  const resp = await fetch(endpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!resp.ok) {
    const errTxt = await resp.text().catch(() => "");
    throw new Error(`Gemini image API error ${resp.status}: ${errTxt}`);
  }

  const json = await resp.json();
  // Navegamos la estructura para extraer inlineData
  // Esperado: candidates[0].content.parts[0].inlineData.{data,mimeType}
  const candidates = json?.candidates || [];
  const parts = candidates[0]?.content?.parts || candidates[0]?.content || [];
  let inlineData = null as null | { data: string; mimeType?: string };

  for (const p of parts) {
    if (p?.inlineData?.data) { inlineData = p.inlineData; break; }
  }

  if (!inlineData?.data) {
    throw new Error("Gemini image API: no inline image data found in response");
  }

  const outMime = inlineData.mimeType || "image/jpeg";
  const buffer = Buffer.from(inlineData.data, "base64");
  return { buffer, contentType: outMime };
}

